### PR TITLE
Update jsdoc to address feedback from #3382

### PR DESCRIPTION
**Pull request by macleodbroad-wf**
@wimrijnders had feedback on 3382 that was unaddressed prior to merge.

I have addressed the majority of the feedback.
- [x] Correct use of `@static`
- [x] Correct unresolvable/incorrectly name-spaced types
- [x] Remove extraneous `@class` and `@constructor` from explicitly defined classes & constructors (note: added `@inheritDoc` to constructors to satisfy linter)

I will address the rest of the feedback around unreadable/overly complex types in a follow-up PR, as they will require code changes beyond just jsdoc.

R: @wimrijnders & @yotamberk

### CODE REVIEW

**Comment by macleodbroad-wf** [comment]
Passes locally. Likely to pass on re-build.

**Comment by yotamberk** [comment]
I sent a rebuild and still not passing

**Comment by macleodbroad-wf** [comment]
Will review, thank you

**Comment by macleodbroad-wf** [comment]
Odd, still passing locally

**Comment by wimrijnders** [comment]
Oh man. This looks like unit testing issues. I'll have a look if I can reproduce the unit tests failing locally.

**Pull request closed without merging**
