### PR TITLE
Fix infinite loop on drawing of large labels

### PR DESCRIPTION
**Pull request by wimrijnders**
Fix for #3171 and #3185.

- Fixed the infinite loop which can occur in specific case when drawing node labels.
- Labels with one huge word longer than width constraint are now broken into multiple lines.

This can lock up `Network` due to the infinite loop, so I feel that the PRIORITY label is in order here. You can't have that happening in cases that users would regard as 'normal usage'.

The actual fix for the issue (see above) is the code in function `splitStringIntoLines()`.

----
Changes:

- Added new local class `LabelAccumulator` to `Label.js`. This moves away recurring actions within the main loops of the label handling.
- Moved code specific to splitting up label text to new method `Label._processLabelText()`
- Added unit tests for this method
- Added unit tests for proper handling of html and markdown tags
- Added unit tests for checking proper handling of `widthConstraint.maximum`.
- Added commenting, notes and TODO's where appropriate.

### CODE REVIEW

**Comment by wimrijnders** [comment]
### Some extra info

I'm afraid that this fix is going to be pretty tough to review, if you're relying on diffing.
The code in question has changed significantly; it was pretty convoluted, and I found myself cleaning it up and refactoring just to understand it. It was not my intention at all to make such a drastic change, but I believe it is for the better.

The goal of this refactoring is to make the code for the label splitting clearer.
This does not mean it has become simpler, but the code has been rearranged to make it more understandable.

I have added unit tests to be sure that all is working as expected. This also tests the markup and tags for when using multi-fonts. The unit tests may be expanded in the future.

The actual fix for the issue (see above) is the code in function `splitStringIntoLines()`.

----
Changes:

- Added new local class `LabelAccumulator` to `Label.js`. This moves away recurring actions within the main loops of the label handling.
- Moved code specific to splitting up label text to new method `Label._processLabelText()`
- Added unit tests for this method
- Added unit tests for proper handling of html and markdown tags
- Added unit tests for checking proper handling of `widthConstraint.maximum`.
- Added commenting, notes and TODO's where appropriate.

**Comment by jmvenancio** [comment]
I started testing and found a problem already :( @wimrijnders 

[(https://i.gyazo.com/6e9c441b4045c43a780ab2861a836458.mp4)]

**Comment by jmvenancio** [comment]
It only happens after the zoom exceed 1.2

**Comment by wimrijnders** [comment]
@jmvenancio What exactly is the problem? What I see is that the particular subject of this fix works as expected.

Perhaps you mean the 'flash' that happens when the node height is larger than the view height? And the whole view turns the color of the node? I would call this a separate issue, and to be honest not a very critical one. But perhaps you differ in opinion of this.

**Comment by jmvenancio** [comment]
@wimrijnders you're right. It is a different issue. Although it still does not work as expected, because on that particular case the width constraint is broken. And of course that is not a critical issue, I will continue testing but I'll mention this problem on the review.

Thank you for all your work!!

**Comment by wimrijnders** [comment]
> you're right. It is a different issue.

@jmvenancio If it really bothers you, please make a new issue out of it.

As for the second issue, you mean the overflow in the big rectangle on the left, right?
It looks like there's a max height constraint on that rectangle. I only handled the width in this fix, and my thought is that then the overflow is a separate issue. If it's not due to a max height constraint, please show me example code that produced that.

I have to say you're very much stress-testing this fix. I would also say that that is a good thing.

**Comment by jmvenancio** [comment]
I am not really sure it is only about the height constraint. Notice on the left green box, the "a a a" goes out of the rectangle, on the other hand on the right green box the "bolas bolas" does not go out and it has a superior height. And I set the maximum height to the height of the small rectangles so, maybe two issues should be created.

In my specific case this fix isn´t enough since I really want all the nodes to have the same size. Also I think that the maximum height constraint should always be respected, much like width constraint is with this fix... And maybe this is another issue...

**Comment by wimrijnders** [comment]
@jmvenancio Could you give me the code that made the previous screen dump? I'd like to examine that in more detail.

**Comment by yotamberk** [comment]
@wimrijnders what's the status for this PR? Can it be reviewed?

**Comment by wimrijnders** [comment]
@yotamberk Yes, it can definitely be reviewed. The core issue here is the fix on infinite loop. The discussion here is about an edge case with respect to layout.

@jmvenancio Could you open a new issue, please, for the overflowing of the big labels? I think it is worthwhile to pursue this, but not in the current PR. Thanks.

**Comment by wimrijnders** [comment]
@Maniae That went straight into the unit tests. Unfortunately, the test succeeds. Would you mind adding some minimal code in order to reproduce the error?

I'm hereby assuming that you are using the `develop`-branch, since `LabelAccumulator is not in production yet. If I can confirm this, I'm going to ask you to open a new issue on this.

In any case, thanks for reporting!

**Pull request merged**
