### PR TITLE
Add specific class with value to major gird lines

### PR DESCRIPTION
**Pull request by leninzprahy**
It will be possible to highlight specific lines, for example in rpercentage chart 100%, by adding `.vis-val-100 {}` to css...

### CODE REVIEW

**Comment by AlexDM0** [comment]
This is what the timebars are for. Check the custom time examples.

Regards

**Comment by leninzprahy** [comment]
I think, that timebars are for vertical lines, but this PR only add class to horizontal lines in grid.
For example in Graph2d

**Comment by AlexDM0** [comment]
I see, @ludost what do you think? We cannot accept pull requests on the master branch, only develop.

Cheers

**Comment by leninzprahy** [comment]
I understand. Should I to send the PR to the develop branch?

**Comment by AlexDM0** [comment]
I have the feeling there should be a better solution for this usecase.. @ludost is currently maintaining the graph2d so I'll let him decide.

Regards

**Pull request closed without merging**
