### PR TITLE
make bundleing with webpack possible

### PR DESCRIPTION
**Pull request by mojoaxel**
I moved the following dependencies from `devDependencies` to `dependencies`:
* emitter-component
* moment
* propagating-hammerjs
* hammerjs
* keycharm

I use the timeline component in a project. If I include `dist/vis-timeline-graph2d.min.js` i have the problem that `moment` and `hammerjs` are included twice.

So the best way ist to include `/vis-timeline-graph2d.js` with webpacks babel-loader and let the module-bundler figure out the rest. So I don't want to build my own `dist` version, but want to resolve the dependencies "on the fly". This is also recessary for things like [tree shaking](https://medium.com/@Rich_Harris/tree-shaking-versus-dead-code-elimination-d3765df85c80#.eo0uxcn8t) and other fancy stuff.

The only think that has to be changed for that ist to install the needed dependencies together with vis itself. Voila!

I tried it and it works with webpack. The vis code now is only half the size!

### CODE REVIEW

**Comment by mojoaxel** [comment]
this "fixes" #1866

**Comment by yotamberk** [comment]
Hi @mojoaxel, 
Can you fix the conflicts and submit the fix?
I want to add this in =)

**Comment by mojoaxel** [comment]
> Can you fix the conflicts and submit the fix?

done.
@yotamberk Can you please make sure that this fix does not break anything. Thanks!

**Comment by yotamberk** [comment]
It seems to be working fine!
I'm merging it =)

**Comment by mojoaxel** [comment]
Yeah!! Thanks!

**Pull request merged**
