### PR TITLE
Draw points only if they have an itemlabel

### PR DESCRIPTION
**Pull request by mschallar**
Hello,

I implemented my own feature request from https://github.com/almende/vis/issues/1018 

This option can be set for a Group or the Graph2d. The Group setting overwrites the Graph2d setting.
I've updated the docs and the 19_labels example as well.

Please let me know if there is anything else to do.

Regards,
Manuel

### CODE REVIEW

**Comment by AlexDM0** [comment]
Hi,

We cannot accept pull requests to master. All requests have to go into develop. 

I wonder, would it be cleaner to set an override called something like showPoints to groups and items? That way you can chose in the group to hide all points and in the specific item to show it or the other way around. I think it would be more flexible and achieve the same result. 

What do you think? These very specific options are very much bound to a single usecase. I prefer options that allow multiple usages. 

Regards

**Comment by mschallar** [comment]
Sorry about the master/develop, I thought I had clicked almende:develop :-(.

Regarding your idea.
Sounds good at first glance, but:

This would mean that the server which provides the JSON data for all the items has to add the information whether to draw the point or not to **every** item which makes him somehow responsible for the view, this means:

1. The decision has to be made on the server whether to draw the point or not by setting the flag
2. The client (i.e., the options defined by the client) can not override it because the "item option" would overrule the "group option" and even the "graph2d" option.

IMHO is the client responsible for the view i.e., how the items received should be drawn. This must not be done on the server side, the server is responsible for the data. Means further that the server will attach item labels so items, and some items will not have a label. It's the client decision whether to draw those items or not, therefore the option 'onlyifLabelExists' sounds good to me.

Why to **every** item?
The server may not know have any information about the client's options. If the server should be responsible for the view (according to your idea) he must generate a valid view i.e., attaching to every  item the 'drawPoint' information. May also increase the JSON size significantly as well.

Hope to get your feedback.

Regards,
Manuel

**Comment by AlexDM0** [comment]
Hi Manuel,

I agree that the server should not have to do this, but there is also the option of adding a preprocessor on the client side that checks if label exists and if yes, adds the exception to the item.

I figured something like [{x:x,y:y},{x:x,y:y},{x:x,y:y},{x:x,y:y},{x:x,y:y,label:'bla',point:true},{x:x,y:y},{x:x,y:y},{x:x,y:y}] would be clean? Another option would be to allow a callback function to be given, point could be true, false or function. the function would get information on the datapoint as an argument and returns true or false? or true false or object with information like radius and shape?

Regards

**Comment by mschallar** [comment]
Hi Alex,

If you want callbacks for each individual datapoint than they can not be inside items like

    {
      x: x,
      y: y,
      label: 'bla',
      point: function (item, group, graph2d, whateverParameter, ...)  {
                  return true;
             }
    }

How should the server generate such a callback on an item? Not feasible IMHO. An alternative would be so add such a callback to the Graph2d options.

I think we (you) should even replace the `drawPoints.enabled` parameter from `true/false` to `true/false/function` instead of adding a new parameter.

    drawPoints {
      enabled: function(item) {
        // here we can access item, the group (by the item's groupid) and the graph2d (over the framework variable) and decide whether to draw the datapoint or not.
      }
    }

Yes, it's even an possibility for the function to return an object, containing more information about the drawing style of that data point like:

    return {
      style: 'square', // square, circle, according to docs
      size: 6 // the size of the data point, according to docs
    }

These 'square' and 'size' parameters could override the parameters for Group/Graph2d.

Regards,
Manuel

**Comment by AlexDM0** [comment]
Hi Manuel,

Yes, I ment the callback at the graph2d or the group level, not the points. We would probably do it like so:

```
drawPoints: {enabled, style, size}  

OR 

drawPoints: true/false/function
```
where the function would return true/false/{style:x,size:x}

Would you like to implement this?

Regards

**Comment by mschallar** [comment]
Yes I will. I'll do it on the Graph2d level, sounds better to me.

**Comment by AlexDM0** [comment]
I think it should be over ridable in the groups though, different groups could have different requirements :)

**Comment by mschallar** [comment]
You can access the group within the callback. There you can decide according to the groups policy whether to draw or not.

It's quite the same with the discussion Group vs. Graph2d option, as it was back an hour ago.
The groups could be provided by the server together with the items.

The only thing not provided by the server is the Graph2d's options. I think it's safest to update the options there. If there would be a separation between the actual groups, and the group options, your solution would work as well.

**Comment by AlexDM0** [comment]
This is fully dependent on the architecture of your system. In your case the group settings may come form the server, in a lot of my cases I get pure x y data from servers and put them in groups with a preprocessor on the client side. 

Hence if the callback can be defined in groups as well as graph2d, it is the best of both worlds. In your case you can configure everything in the graph2d, in my case I can make callbacks for different groups.

Regards

**Comment by mschallar** [comment]
Ok, I'll do it your proposed way. Will take a few days.

**Comment by mschallar** [comment]
Few days are over ;)
New pull request: https://github.com/almende/vis/pull/1030

**Pull request closed without merging**
