### PR TITLE
Use requestAnimationFrame to throttle redraws

### PR DESCRIPTION
**Pull request by gkubisa**
It allows the browser to determine the best rate at which redraws should happen and avoids choppy scrolling when Chrome starts throttling `setTimeout` (see https://docs.google.com/document/d/163ow-1wjd6L0rAN3V_U6t12eqVkq4mXDDjVaA4OuvCA/edit#)

### CODE REVIEW

**Comment by mojoaxel** [comment]
@gkubisa Thanks very much! Thats a good idea! It may be even fix #2023.

Could you please remove the changes in the `dist` folder. We normally no not update this folder in the developing branch. This should work something like this:
```
git reset HEAD~1 dist
git commit --amend --no-edit
git push --force
```

**Comment by gkubisa** [comment]
@mojoaxel, I've just removed those changes to the `dist` directory

**Comment by yotamberk** [comment]
@mojoaxel This merge is causing a serious problem with the throttle redraw. I causes asynchronous behavior and causes  #2307. 
I don;t know how to solve this problem. I think we need to revert this merge.

**Comment by gkubisa** [comment]
@yotamberk, reverting this PR would cause another regression (#2023). Would it be possible to just trigger synchronous redraw on initialization? If necessary, certain other actions could also trigger a synchronous redraw, eg updating the chart data programmatically.

**Comment by yotamberk** [comment]
@gkubisa I understand. I've tried solving the bug it caused without much success... Can you take a look at this?

**Comment by yotamberk** [comment]
Nvm, I've submitted a PR to solve the async problem (#2386)

**Pull request merged**
