### PR TITLE
label stroke

### PR DESCRIPTION
**Pull request by klmdb**
Added label stroke support to Nodes, Edges & Groups as per-object or
global settings. Use `fontStrokeWidth` & `fontStrokeColor` (default
values: 0 & 'white').
.
Note this is the first time I've tried to create a pull-request. Please let me know if I'm doing something wrong ;)

Regards,
klmdb

### CODE REVIEW

**Comment by AlexDM0** [comment]
Hi Klmdb,

Could you remove the dist files from the commit and add an example? Thanks for the contribution!

Regards,

Alex

**Comment by klmdb** [comment]
I added a small fix regarding stroke spiking and an example.

I don't really know how to modify this pull request to apply that commit to it and exclude the dist files. Any help? This is the first time I contribute on github ;)

**Comment by AlexDM0** [comment]
Hi,

I'll try to merge is as-is. Thank you for the example!

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi Klmdb,

I have manually merged this into develop. I'm not exactly sure why git didn't pick up on the merge but I can close this now. Even though it'll say I didnt merge, you can check in develop that your example and code is in there. I made some minor tweaks to the code for optimization and I have credited you in the history.md file.

Regards and thanks again!

Alex

**Pull request closed without merging**
