### PR TITLE
Bug fix for null parent

### PR DESCRIPTION
**Pull request by danny-larsen**
This fixes an error on updating items in nested groups

### CODE REVIEW

**Comment by yotamberk** [comment]
@danny-larsen can you reference the issue this solves?

**Comment by danny-larsen** [comment]
No sorry. I didn't have time to make an issue. But it is just one line and it seems like an error to me that other places in that function the parent is checked for null before accessing it. Maybe @yotamberk can help. I can see that he added it?

**Comment by yotamberk** [comment]
Funny, I am @yotamberk :laughing:

**Comment by danny-larsen** [comment]
Ha. I guess I was a bit quick there :)

**Pull request merged**
