### PR TITLE
[Timeline][Feature] Implementation of getVisibleGroups

### PR DESCRIPTION
**Pull request by MeTaNoV**
Implement Issue #3658 

Use-Case:
This enabled us to have the possibility to use only vertical scroll to move the window to follow some issue presented with a Gantt style. Here is a snippet of the integration:
```js
this._timeline.on("scroll", (e) => {
  let vGroups = this._timeline.getVisibleGroups()
  let vItems = vGroups.reduce((res, groupId) => {
  let group = this._timeline.itemSet.groups[groupId]
  if (group.items) {
    res = res.concat(Object.keys(group.items))
  }
  return res
  }, [])
  this._timeline.focus(vItems)
})
```
Note:
This might be a bug, the `scroll` event is not triggered on the label column, therefore the code above is only working on the main area. I'll raise an other issue and try to see if I can fix that.

---
This change is [Reviewable](https://reviewable.io/reviews/almende/vis/3660)

### CODE REVIEW

**Comment by MeTaNoV** [comment]
Concerning my note, I just discovered the `scrollSide` event which is triggered on the left/right panel. I didn't see it anywhere in the docs however! ;)

**Comment by mbroad** [comment]
This looks interesting. Would you consider adding an example to the example pages?

**Comment by MeTaNoV** [comment]
Sure, let me do that.

**Comment by yotamberk** [comment]
The PR has been implemented on the wrong branch :cry: Can you please re-do your implementations on a new branch taken from the `develop` branch?
We really do appreciate the contribution but I have to close this PR since I cannot accept it like this in to the `master` branch

**Comment by MeTaNoV** [comment]
@yotamberk , sure, I'll do it from the develop bracnh if this is the way to go! see you soon!

**Comment by yotamberk** [comment]
Awesome! Looking forward to this PR

**Comment by mbroad** [comment]
@metanov - are you still working on this or do you need someone to carry it?

**Comment by MeTaNoV** [comment]
@mbroad, my newest PR has been already merged! ;)

**Pull request closed without merging**
