### PR TITLE
Consolidated code for drawing x-axis label

### PR DESCRIPTION
**Pull request by wimrijnders**
The drawing of the axis labels occurs in two places and are chunks of non-trivial code. Hence I think it is a good idea to consolidate these.

This PR contains a new single method for drawing labels for the x-axis. If you can agree with this, I will do the y and z axis labels in a similar manner. Awaiting your response.

### CODE REVIEW

**Comment by wimrijnders** [comment]
OK, fine with me.
If you're both good with it, perhaps I can add the Y and Z label handling to this PR as well.

**Comment by yotamberk** [comment]
That sounds good to me

**Comment by mojoaxel** [comment]
@wimrijnders Looks good. Feel free to add more changes concerning the axis labels.

**Comment by wimrijnders** [comment]
Ok. I'm missing my upward thumb emoticon here - (y) in skype.

Will do it this afternoon, have some other tasks now.

**Comment by wimrijnders** [comment]
Oh, merged already. Never mind, I'll make a new PR for the Y and Z labels.

**Comment by mojoaxel** [comment]
> Ok. I'm missing my upward thumb emoticon here - (y) in skype.

start with a ":"

**Comment by wimrijnders** [comment]
:+1: Ha! Thank you. Very important, this.

**Pull request merged**
