### PR TITLE
#3246 - fix issue when showMajorLabels == false is used with a weekly scale.

### PR DESCRIPTION
**Pull request by ponml**
The referencing issue's example (#3246) should be sufficient to see the fix. This is my very first PR to this repo, and I'm hoping I've followed all the guidelines properly, so please let me know if not.

From what I can gather, there is some special logic to handle the creation of TimeSteps when a week crosses over a month (which is the `Major` unit for weekly mode).

This logic needs to be ignored if `showMajorLabels` is set to false.

-Chris.

### CODE REVIEW

**Comment by yotamberk** [comment]
Awesome! Great job!

**Comment by yotamberk** [comment]
@ponml can you please address the issue occurring with this PR: https://github.com/almende/vis/issues/3246#issuecomment-321995229

**Comment by ponml** [comment]
@yotamberk I'm a bit confused on the exact issue happening. Is it a matter of reverting my change, as the extra step is an intended feature? Or rather, is it that there seems to be something wrong in the labeling in the weekStyling.html example since merging this PR?

**Comment by yotamberk** [comment]
The example seemed to have broke. This means that the application of your fix broke something else. I agree with this implementation of the bug fix, but this causes another bug to pop out

**Comment by ponml** [comment]
Alright, I can take a look 👍

**Comment by ponml** [comment]
#3361 -> fix for the minor labelling

**Pull request merged**
