### PR TITLE
added RailRoad SRFB showcase

### PR DESCRIPTION
**Pull request by gbrault**
added RailRoad SRFB showcase #2563 #2569

Hope its good now!

### CODE REVIEW

**Comment by gbrault** [comment]
@mojoaxel  Sorry, but I got stuck and made a mistake:  could you please do it for me as I deleted the fork (I had a error uploading the new image and everything went on the wrong side since then!)
I agree with the picture.
Thanks again.

**Comment by mojoaxel** [comment]
>  could you please do it for me as I deleted the fork

No problem!

**Comment by gbrault** [comment]
Thanks @mojoaxel have a good week-end!

**Comment by mojoaxel** [comment]
Images size adjusted with 3219c5d

**Pull request merged**
