### PR TITLE
add template support for minor/major labels

### PR DESCRIPTION
**Pull request by yotamberk**

### CODE REVIEW

**Comment by Tooa** [comment]
Do we need some kind of documentation for this feature either via an example or mentioning it in the documentation?

**Comment by yotamberk** [comment]
I think it's very rare that someone would use it, but if they do, they can. I don't think it need s documentation

**Comment by ShawnMercado** [comment]
Is there any information about how to use this feature?

**Comment by yotamberk** [comment]
@ShawnMercado  checkout this example http://visjs.org/examples/timeline/other/functionLabelFormats.html

**Pull request merged**
