### PR TITLE
Fixed the two broken references to SweetAlert

### PR DESCRIPTION
**Pull request by sandebert**
The urls I used where the best ones I managed to find. (I'm sure there are better ones somewhere, but it was surprisingly difficult finding them.)

### CODE REVIEW

**Comment by sandebert** [comment]
Sorry, I should have mentioned this relates to http://visjs.org/examples/timeline/editing/editingItemsCallbacks.html, which is broken due to 404s for the SweetAlert references.

**Comment by sandebert** [comment]
Oh, I made a bad assumption here. I just assumed the files had changed locations and that I just needed to update the references so I just updated the urls and PR'd.

So what do you say, are these reasonable urls instead?

- https://cdn.jsdelivr.net/npm/sweetalert@1.1.3/lib/sweetalert.min.js
- https://cdn.jsdelivr.net/npm/sweetalert@1.1.3/dist/sweetalert.css

**Comment by Jogai** [comment]
Yes, I would say so.

**Comment by yotamberk** [comment]
hi @sandebert 
I've now branched out to a new fork of my own including only Timeline.
I've applied your change here: https://github.com/yotamberk/timeline-plus
and can be used via npm here: https://www.npmjs.com/package/timeline-plus
Awesome fix! Thanks for your contribution! Future PRs will be reviewed and added in the new fork

**Pull request merged**
