### PR TITLE
#2839 - Corrects documentation for DataSet get and how multiple missi…

### PR DESCRIPTION
**Pull request by macleodbroad-wf**
…ng ids are handled.

### CODE REVIEW

**Comment by macleodbroad-wf** [comment]
R: @wimrijnders @mojoaxel

**Comment by macleodbroad-wf** [comment]
Originally I had written a `fix`, that excluded unfound entries, but I would consider that a backwards breaking change, and after some reflection, I'm not sure it is a better API.

I prefer APIs with a symmetrical input and output for cases like this.

For example:
```
input: [nodeId1, missingNodeId, nodeId2]
output: [<Instance of Node1>, null, <instance of Node2>]
```
 if I pass in a list of 3 arguments, I expect a list of length 3 back, with nulls for anything that was missing, and I expect those results in the order that I had passed in the arguments. 

To me, this better follows the [Principle of Least Astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

Also, it is already implemented in the way I describe, and to change it now would be surprising to consumers, who would now have to cycle through the result list, checking node ids, to understand which nodes were found and which were not.

**Comment by macleodbroad-wf** [comment]
Should this also be opened against develop?

**Comment by wimrijnders** [comment]
Wrt. nulls in returned array: I understand your reasoning perfectly, and the argument for not changing the output is good. However, I personally would be least astonished if `null`'s were *not* returned.

OK, how about this idea: add an option for returning `null`'s or not. The default would be to do what it does now, thereby breaking no-one's code. But removal of the `null`'s can be  set in options.

> Should this also be opened against develop?

Aargh! I missed that. Yes, `develop`.

**Pull request closed without merging**
