### PR TITLE
Fixes for removing and adding items to subgroups

### PR DESCRIPTION
**Pull request by BTMorton**
Added methods to remove and add items to a subgroup.
Added a method to change the subgroup an item is in, rather than removing it from the group entirely and then re-adding.
No longer decrement subgroup ID when removing a subgroup, as this can cause collisions if you remove the last item from a group and then add another one to it.
This should fix the issues found in #2594

### CODE REVIEW

**Comment by bradh** [comment]
Seems like a good candidate for some unit tests.

**Comment by bradh** [comment]
@BTMorton do you need a hand with the tests?

**Comment by BTMorton** [comment]
Oh, sorry, I didn't realise you actually had a test framework yet, or that you wanted me to do them :P I can take a look at it, but if you wanted to suggest some test cases, that wouldn't be unhelpful :D

**Comment by yotamberk** [comment]
@BTMorton What's the status of the tests? 
@bradh I think we should accept this PR and get the tests in in a separate PR. What do you think?

**Comment by BTMorton** [comment]
Sorry, I haven't had the chance yet. As you can probably imagine, the fix is more important to the company than writing the tests...

**Comment by yotamberk** [comment]
Merging this PR. Tests will be added in future PRs

**Pull request merged**
