### PR TITLE
chore(lint): eslint minimal rules; babel-eslint parser; travis

### PR DESCRIPTION
**Pull request by AoDev**
Hello,

I am interested in contributing, mainly to the network, so I cloned the repo.

I realised that there is no proper linting defined in the project. So my first PR is about solving this.
Since I don't know what code style you wish, I have added `eslint:recommended` as a starting point.

Let's discuss it. Unless you lint it in a different way or you are not interested ;)

Errors with current config. (We should fix when we are sure of what style to use)

```
/Volumes/DataUser/git-repos/3rd/vis/lib/DataSet.js
  267:9   error  Unexpected console statement      no-console
  324:35  error  'args' is defined but never used  no-unused-vars

/Volumes/DataUser/git-repos/3rd/vis/lib/DataView.js
  161:36  error  'args' is defined but never used  no-unused-vars

/Volumes/DataUser/git-repos/3rd/vis/lib/graph3d/Camera.js
   54:42  error  'y' is defined but never used            no-unused-vars
  168:7   error  'ya' is assigned a value but never used  no-unused-vars

/Volumes/DataUser/git-repos/3rd/vis/lib/graph3d/Filter.js
   43:2  error  Unnecessary semicolon                                no-extra-semi
  184:9  error  'dataPointsTemp' is assigned a value but never used  no-unused-vars

/Volumes/DataUser/git-repos/3rd/vis/lib/graph3d/Graph3d.js
     6:5   error  'Camera' is assigned a value but never used                          no-unused-vars
   419:56  error  'style' is defined but never used                                    no-unused-vars
   702:55  error  'onkeydown' is not defined                                           no-undef
   844:7   error  'cameraPosition' is assigned a value but never used                  no-unused-vars
   905:7   error  Unreachable code                                                     no-unreachable
  1068:7   error  'y' is already defined                                               no-redeclare
  1259:33  error  This function has too many statements (114). Maximum allowed is 100  max-statements
  1341:11  error  'msg' is already defined                                             no-redeclare
  1367:11  error  'msg' is already defined                                             no-redeclare
  1493:7   error  'i' is defined but never used                                        no-unused-vars
  1802:7   error  'lineWidth' is defined but never used                                no-unused-vars

/Volumes/DataUser/git-repos/3rd/vis/lib/graph3d/Point3d.js
  11:2  error  Unnecessary semicolon  no-extra-semi

/Volumes/DataUser/git-repos/3rd/vis/lib/graph3d/Slider.js
  187:45  error  'interval' is defined but never used  no-unused-vars
  336:41  error  'event' is defined but never used     no-unused-vars

/Volumes/DataUser/git-repos/3rd/vis/lib/graph3d/StepNumber.js
  36:2  error  Unnecessary semicolon  no-extra-semi

/Volumes/DataUser/git-repos/3rd/vis/lib/hammerUtil.js
  1:5  error  'Hammer' is assigned a value but never used  no-unused-vars

/Volumes/DataUser/git-repos/3rd/vis/lib/network/gephiParser.js
  43:12  error  'i' is already defined  no-redeclare

/Volumes/DataUser/git-repos/3rd/vis/lib/network/Images.js
  39:13  error  Unexpected console statement    no-console
  62:27  error  'id' is defined but never used  no-unused-vars
  79:13  error  Unexpected console statement    no-console

/Volumes/DataUser/git-repos/3rd/vis/lib/network/modules/Canvas.js
  330:4  error  Unnecessary semicolon  no-extra-semi

/Volumes/DataUser/git-repos/3rd/vis/lib/network/modules/Clustering.js
  501:7  error  Unexpected console statement  no-console
  543:7  error  Unexpected console statement  no-console
  836:4  error  Unnecessary semicolon         no-extra-semi

/Volumes/DataUser/git-repos/3rd/vis/lib/network/modules/components/edges/BezierEdgeStatic.js
  41:21  error  Function '_getViaCoordinates' has a complexity of 54  complexity

/Volumes/DataUser/git-repos/3rd/vis/lib/network/modules/components/edges/util/EdgeBase.js
   65:52  error  'toPoint' is defined but never used          no-unused-vars
  132:16  error  'radius' is assigned a value but never used  no-unused-vars
  258:35  error  'hover' is defined but never used            no-unused-vars
  328:50  error  'values' is defined but never used           no-unused-vars

/Volumes/DataUser/git-repos/3rd/vis/lib/network/modules/components/NavigationHandler.js
  1:5  error  'util' is assigned a value but never used  no-unused-vars

/Volumes/DataUser/git-repos/3rd/vis/lib/network/modules/components/Node.js
  19:9   error  'Validator' is defined but never used   no-unused-vars
  20:10  error  'printStyle' is defined but never used  no-unused-vars

/Volumes/DataUser/git-repos/3rd/vis/lib/network/modules/components/nodes/shapes/Circle.js
  11:61  error  'values' is assigned a value but never used  no-unused-vars
  48:25  error  'angle' is defined but never used            no-unused-vars

/Volumes/DataUser/git-repos/3rd/vis/lib/network/modules/components/nodes/shapes/CircularImage.js
  45:9   error  'size' is assigned a value but never used  no-unused-vars
  75:25  error  'angle' is defined but never used          no-unused-vars

/Volumes/DataUser/git-repos/3rd/vis/lib/network/modules/components/nodes/shapes/Dot.js
  18:25  error  'angle' is defined but never used  no-unused-vars

/Volumes/DataUser/git-repos/3rd/vis/lib/network/modules/components/nodes/shapes/Icon.js
  72:7  error  Unexpected console statement  no-console

/Volumes/DataUser/git-repos/3rd/vis/lib/network/modules/components/nodes/shapes/Triangle.js
  10:10  error  'ctx' is defined but never used  no-unused-vars

/Volumes/DataUser/git-repos/3rd/vis/lib/network/modules/components/nodes/shapes/TriangleDown.js
  10:10  error  'ctx' is defined but never used  no-unused-vars

/Volumes/DataUser/git-repos/3rd/vis/lib/network/modules/components/nodes/util/NodeBase.js
  73:9  error  Unexpected console statement  no-console
  86:9  error  Unexpected console statement  no-console

/Volumes/DataUser/git-repos/3rd/vis/lib/network/modules/components/physics/HierarchicalSpringSolver.js
  76:9  error  'springForce' is already defined  no-redeclare

/Volumes/DataUser/git-repos/3rd/vis/lib/network/modules/components/shared/Label.js
  519:28  error  'override' is assigned a value but never used                                   no-unused-vars
  636:28  error  'override' is assigned a value but never used                                   no-unused-vars
  758:16  error  Function '_processLabel' has too many statements (107). Maximum allowed is 100  max-statements
  761:9   error  'nlLines' is assigned a value but never used                                    no-unused-vars

/Volumes/DataUser/git-repos/3rd/vis/lib/network/modules/LayoutEngine.js
   218:15  error  Unexpected console statement                           no-console
   297:11  error  'definedPositions' is assigned a value but never used  no-unused-vars
   330:9   error  Unreachable code                                       no-unreachable
   544:16  error  'min1' is assigned a value but never used              no-unused-vars
   544:27  error  'minSpace1' is assigned a value but never used         no-unused-vars
   544:38  error  'maxSpace1' is assigned a value but never used         no-unused-vars
   545:21  error  'max2' is assigned a value but never used              no-unused-vars
   545:38  error  'maxSpace2' is assigned a value but never used         no-unused-vars
   647:16  error  'minBranch' is assigned a value but never used         no-unused-vars
   647:27  error  'maxBranch' is assigned a value but never used         no-unused-vars
  1079:49  error  'edge' is defined but never used                       no-unused-vars
  1227:9   error  Unexpected console statement                           no-console

/Volumes/DataUser/git-repos/3rd/vis/lib/network/modules/ManipulationSystem.js
   703:11  error  'deleteBtnClass' is already defined  no-redeclare
   844:25  error  'event' is defined but never used    no-unused-vars
  1081:9   error  Unreachable code                     no-unreachable

/Volumes/DataUser/git-repos/3rd/vis/lib/network/modules/NodesHandler.js
  451:7  error  Unexpected console statement  no-console
  470:7  error  Unexpected console statement  no-console

/Volumes/DataUser/git-repos/3rd/vis/lib/network/modules/PhysicsEngine.js
  601:7  error  Unexpected console statement  no-console

/Volumes/DataUser/git-repos/3rd/vis/lib/network/modules/View.js
  114:7  error  Unexpected console statement  no-console
  268:4  error  Unnecessary semicolon         no-extra-semi

/Volumes/DataUser/git-repos/3rd/vis/lib/network/Network.js
    6:5   error  'DataSet' is assigned a value but never used   no-unused-vars
    7:5   error  'DataView' is assigned a value but never used  no-unused-vars
  148:7   error  Unexpected console statement                   no-console
  315:5   error  Unexpected console statement                   no-console
  323:5   error  Unexpected console statement                   no-console
  446:53  error  Unexpected console statement                   no-console

/Volumes/DataUser/git-repos/3rd/vis/lib/shared/ColorPicker.js
  371:17  error  Empty block statement  no-empty
  381:17  error  Empty block statement  no-empty

/Volumes/DataUser/git-repos/3rd/vis/lib/shared/Configurator.js
  334:17  error  Empty block statement         no-empty
  627:13  error  Unexpected console statement  no-console

/Volumes/DataUser/git-repos/3rd/vis/lib/shared/Validator.js
   95:11  error  Unexpected console statement  no-console
  111:7   error  Unexpected console statement  no-console
  170:7   error  Unexpected console statement  no-console
  173:7   error  Unexpected console statement  no-console
  176:7   error  Unexpected console statement  no-console
  179:7   error  Unexpected console statement  no-console
  296:1   error  Unnecessary semicolon         no-extra-semi

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/component/BackgroundGroup.js
   1:5   error  'util' is assigned a value but never used  no-unused-vars
  28:60  error  'restack' is defined but never used        no-unused-vars

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/component/Component.js
  8:27  error  'options' is defined but never used  no-unused-vars

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/component/CurrentTime.js
  95:9  error  Unexpected console statement  no-console

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/component/CustomTime.js
  135:7  error  Unexpected console statement  no-console

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/component/DataScale.js
  170:7  error  'lines' is assigned a value but never used  no-unused-vars
  212:9  error  Unexpected console statement                no-console

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/component/graph2d_types/bar.js
    4:28  error  'options' is defined but never used           no-unused-vars
    9:7   error  'path' is defined but never used              no-unused-vars
    9:13  error  'fillPath' is defined but never used          no-unused-vars
  109:11  error  'prevKey' is assigned a value but never used  no-unused-vars

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/component/graph2d_types/line.js
    3:24  error  'options' is defined but never used  no-unused-vars
  146:18  error  'i' is already defined               no-redeclare

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/component/graph2d_types/points.js
   3:26  error  'options' is defined but never used   no-unused-vars
  35:7   error  'path' is defined but never used      no-unused-vars
  35:13  error  'fillPath' is defined but never used  no-unused-vars

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/component/GraphGroup.js
  2:5  error  'DOMutil' is assigned a value but never used  no-unused-vars

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/component/Group.js
    3:5   error  'RangeItem' is assigned a value but never used  no-unused-vars
  277:7   error  'foreground' is already defined                 no-redeclare
  494:16  error  'subgroup' is already defined                   no-redeclare
  637:12  error  'i' is already defined                          no-redeclare
  662:14  error  'i' is already defined                          no-redeclare
  663:11  error  'item' is already defined                       no-redeclare

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/component/item/BackgroundItem.js
    1:5   error  'Hammer' is assigned a value but never used         no-unused-vars
  144:49  error  'margin' is defined but never used                  no-unused-vars
  153:9   error  'subgroupIndex' is assigned a value but never used  no-unused-vars

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/component/item/BoxItem.js
  2:5  error  'util' is assigned a value but never used  no-unused-vars

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/component/item/Item.js
   45:6   error  Unnecessary semicolon                    no-extra-semi
   88:20  error  'options' is not defined                 no-undef
  121:37  error  'range' is defined but never used        no-unused-vars
  252:9   error  'me' is assigned a value but never used  no-unused-vars
  378:9   error  'changed' is already defined             no-redeclare

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/component/item/RangeItem.js
  1:5  error  'Hammer' is assigned a value but never used  no-unused-vars

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/component/ItemSet.js
    38:50  error  'groups' is defined but never used               no-unused-vars
    39:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
    40:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
    41:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
   129:37  error  'senderId' is defined but never used             no-unused-vars
   132:40  error  'senderId' is defined but never used             no-unused-vars
   135:40  error  'senderId' is defined but never used             no-unused-vars
   142:37  error  'senderId' is defined but never used             no-unused-vars
   145:40  error  'senderId' is defined but never used             no-unused-vars
   148:40  error  'senderId' is defined but never used             no-unused-vars
   541:9   error  'left' is already defined                        no-redeclare
   542:9   error  'right' is already defined                       no-redeclare
   693:7   error  'background' is assigned a value but never used  no-unused-vars
   885:7   error  'itemObj' is assigned a value but never used     no-unused-vars
  1181:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1183:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1205:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1207:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1374:9   error  'xAbs' is already defined                        no-redeclare
  1375:9   error  'x' is already defined                           no-redeclare
  1435:11  error  'xOffset' is already defined                     no-redeclare
  1466:13  error  'offset' is already defined                      no-redeclare
  1502:19  error  'initialStart' is already defined                no-redeclare
  1503:19  error  'start' is already defined                       no-redeclare
  1509:19  error  'initialEnd' is already defined                  no-redeclare
  1510:19  error  'end' is already defined                         no-redeclare
  1520:17  error  'initialStart' is already defined                no-redeclare
  1521:17  error  'start' is already defined                       no-redeclare
  1524:19  error  'initialEnd' is already defined                  no-redeclare
  1678:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1679:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1728:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1729:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1799:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1803:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1804:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1805:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1806:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1807:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1808:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1810:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1811:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1812:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1813:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1814:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1815:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1816:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1817:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1818:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1819:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1820:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1821:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1822:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1823:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1824:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1831:7   error  'groupsData' is not defined                      no-undef
  1832:7   error  'groupsData' is not defined                      no-undef
  1833:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1834:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1835:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1836:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1837:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1838:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1839:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  1840:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  2015:11  error  'xAbs' is already defined                        no-redeclare
  2016:11  error  'x' is already defined                           no-redeclare
  2049:13  error  'end' is already defined                         no-redeclare
  2095:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs
  2103:2   error  Mixed spaces and tabs                            no-mixed-spaces-and-tabs

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/component/Legend.js
  176:14  error  'i' is already defined        no-redeclare
  177:11  error  'groupId' is already defined  no-redeclare

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/component/LineGraph.js
    77:37  error  'senderId' is defined but never used           no-unused-vars
    80:40  error  'senderId' is defined but never used           no-unused-vars
    83:40  error  'senderId' is defined but never used           no-unused-vars
    90:37  error  'senderId' is defined but never used           no-unused-vars
    93:40  error  'senderId' is defined but never used           no-unused-vars
    96:40  error  'senderId' is defined but never used           no-unused-vars
   457:16  error  'groupId' is already defined                   no-redeclare
   475:14  error  'i' is already defined                         no-redeclare
   476:11  error  'item' is already defined                      no-redeclare
   477:11  error  'groupId' is already defined                   no-redeclare
   499:14  error  'groupId' is already defined                   no-redeclare
   508:14  error  'groupId' is already defined                   no-redeclare
   515:15  error  'group' is already defined                     no-redeclare
   711:15  error  Unexpected console statement                   no-console
   737:13  error  Expected a 'break' statement before 'case'     no-fallthrough
   739:13  error  Expected a 'break' statement before 'case'     no-fallthrough
   747:13  error  Expected a 'break' statement before 'default'  no-fallthrough
   959:14  error  'i' is already defined                         no-redeclare
  1017:12  error  'i' is already defined                         no-redeclare

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/component/TimeAxis.js
  225:7   error  'current' is assigned a value but never used      no-unused-vars
  229:16  error  'nextIsMajor' is assigned a value but never used  no-unused-vars
  288:7   error  Unexpected console statement                      no-console
  344:4   error  Unnecessary semicolon                             no-extra-semi
  382:4   error  Unnecessary semicolon                             no-extra-semi
  422:4   error  Unnecessary semicolon                             no-extra-semi

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/Core.js
     5:5   error  'DataSet' is assigned a value but never used   no-unused-vars
     6:5   error  'DataView' is assigned a value but never used  no-unused-vars
     7:5   error  'Range' is assigned a value but never used     no-unused-vars
     8:5   error  'ItemSet' is assigned a value but never used   no-unused-vars
   916:7   error  Unexpected console statement                   no-console
  1143:37  error  'event' is defined but never used              no-unused-vars
  1153:37  error  'event' is defined but never used              no-unused-vars

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/DateUtil.js
  133:15  error  Unexpected console statement     no-console
  156:17  error  Unexpected console statement     no-console
  210:12  error  'i' is already defined           no-redeclare
  224:5   error  Unexpected console statement     no-console
  301:13  error  'conversion' is already defined  no-redeclare
  310:13  error  'conversion' is already defined  no-redeclare
  315:13  error  'conversion' is already defined  no-redeclare
  503:7   error  Unreachable code                 no-unreachable

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/Graph2d.js
    1:5  error  'Emitter' is assigned a value but never used  no-unused-vars
    2:5  error  'Hammer' is assigned a value but never used   no-unused-vars
   40:5  error  Unexpected console statement                  no-console
  146:5  error  Unexpected console statement                  no-console

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/optionsTimeline.js
  73:2  error  Mixed spaces and tabs  no-mixed-spaces-and-tabs
  74:2  error  Mixed spaces and tabs  no-mixed-spaces-and-tabs
  75:2  error  Mixed spaces and tabs  no-mixed-spaces-and-tabs
  76:2  error  Mixed spaces and tabs  no-mixed-spaces-and-tabs

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/Range.js
    2:5   error  'hammerUtil' is assigned a value but never used  no-unused-vars
  139:9   error  'animation' is assigned a value but never used   no-unused-vars
  145:9   error  'interval' is already defined                    no-redeclare
  506:10  error  'diffRange' is already defined                   no-redeclare
  650:38  error  'event' is defined but never used                no-unused-vars
  721:9   error  'x' is already defined                           no-redeclare

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/Stack.js
  48:12  error  'i' is already defined  no-redeclare

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/Timeline.js
    1:5   error  'Emitter' is assigned a value but never used     no-unused-vars
    2:5   error  'Hammer' is assigned a value but never used      no-unused-vars
   47:5   error  Unexpected console statement                     no-console
  215:5   error  Unexpected console statement                     no-console
  436:5   error  Move function declaration to function body root  no-inner-declarations
  440:5   error  Move function declaration to function body root  no-inner-declarations
  459:13  error  'startSide' is already defined                   no-redeclare
  460:13  error  'endSide' is already defined                     no-redeclare
  537:9   error  'x' is already defined                           no-redeclare

/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/TimeStep.js
  155:5  error  Expected a 'break' statement before 'case'  no-fallthrough
  156:5  error  Expected a 'break' statement before 'case'  no-fallthrough
  158:5  error  Expected a 'break' statement before 'case'  no-fallthrough
  159:5  error  Expected a 'break' statement before 'case'  no-fallthrough
  160:5  error  Expected a 'break' statement before 'case'  no-fallthrough

/Volumes/DataUser/git-repos/3rd/vis/lib/util.js
   161:36  error  'b' is defined but never used    no-unused-vars
   178:31  error  'b' is defined but never used    no-unused-vars
   198:47  error  'b' is defined but never used    no-unused-vars
   978:9   error  'rgb' is already defined         no-redeclare
  1381:7   error  'comparator' is already defined  no-redeclare

✖ 270 problems (270 errors, 0 warnings)

```

### CODE REVIEW

**Comment by mojoaxel** [comment]
@AoDev Welcome! We definitive could use some help, especially with the network prats. I recommend joining our [gitter chat](https://gitter.im/vis-js/Lobby).

I created issue #2697 to discuss linting...

**Comment by AoDev** [comment]
@mojoaxel I have added the rules you mentioned.

With these rules, there are a few bugs being revealed!  
I don't know the code that well to judge. So, I prefer to ask for some:

__vis/lib/graph3d/Graph3d.js__  
`702:55  error    'onkeydown' is not defined  no-undef`
```
  util.addEventListener(this.frame.canvas, 'keydown', onkeydown);
```
Should there be an event listener for this? or should we remove it?

----

__vis/lib/network/modules/ManipulationSystem.js__  
`1081:9  warning  Unreachable code  no-unreachable`
```
  else {
    throw new Error('The function for add does not support two arguments (data,callback)');
    this.showManipulatorToolbar();
  }
```
Do you want this method to be called before throwing the error in that case?

----

__vis/lib/timeline/component/item/Item.js__  
`88:20  error  'options' is not defined  no-undef`
```
  else if(typeof options.editable === 'object') {
    this.editable = {};
    util.selectiveExtend(['updateTime', 'updateGroup', 'remove'], this.editable, data.editable);
  }
```
I don't know here, either there is a missing argument for an options object or
we would remove it.

----

__/Volumes/DataUser/git-repos/3rd/vis/lib/timeline/component/ItemSet.js__  
`  1831:7  error  'groupsData' is not defined  no-undef`
`  1832:7  error  'groupsData' is not defined  no-undef`
```
groupsData.update(switchGroup);
groupsData.update(shouldBeGroup);
```
Checking the code, I see this line: `var dataset = me.groupsData.getDataSet();`
maybe it was meant to be:
```
groupsData.update(switchGroup);
groupsData.update(shouldBeGroup);
```
??

**Comment by yotamberk** [comment]
@AoDev 
> vis/lib/graph3d/Graph3d.js
`702:55 error 'onkeydown' is not defined no-undef`

It can be removed. 

----

>vis/lib/timeline/component/item/Item.js
`88:20 error 'options' is not defined no-undef`

it should be `this.options`

----

> /Volumes/DataUser/git-repos/3rd/vis/lib/timeline/component/ItemSet.js
`1831:7 error 'groupsData' is not defined no-undef`
`1832:7 error 'groupsData' is not defined no-undef`

As you said it should be: 
`dataset.update(switchGroup);`
`dataset.update(shouldBeGroup);`

Do you want to add these changes to your PR or do you want me to add another PR with these changes?

**Comment by AoDev** [comment]
@yotamberk I'll add these changes.

**Comment by AoDev** [comment]
@yotamberk It is updated. The last point was for `ManipulationSystem`. I see that in other cases, `this.showManipulatorToolbar()` is called. Should we do the same or I remove it?

**Comment by yotamberk** [comment]
@AoDev that's in the Network module. I don't deal with that module. sorry

**Comment by AoDev** [comment]
@mojoaxel I think the last question is for you, then? then we could merge  :)

**Comment by mojoaxel** [comment]
@AoDev Thanks! Really nice improvement!

**Comment by mojoaxel** [comment]
I'll fix the last warning in `ManipulationSystem` later....

**Pull request merged**
