### PR TITLE
Option to add custom vertical bars implemented

### PR DESCRIPTION
**Pull request by aytech**
Hello,
As discussed in #646, I've added the option to spawn more than one custom vertical bars. Each new bar gets an id, and this id is emitted together with time during timechange and timechanged events. 
Also I've added an option to remove the custom vertical bars. 
Example added to 34_add_custom_timebar.html

Regards,
Oleg

### CODE REVIEW

**Comment by AlexDM0** [comment]
Hi Oleg,

Unless my phone app of git is rubbish, it seems you have edited the vis.js file. This file is compiled and is rebuilt all the time. I'm afraid I can't merge anything into that. 

The vis.js file in dist is created from the js files in lib. Could you insert your changes in there?

Regards,

Alex

**Comment by aytech** [comment]
Hi Alex,
Stupid me, I should've thought of that. Your phone app is OK :) I'll transfer the changes into the respective files over the weekend. One question about the commit though - can I keep it as is and commit next changeset on top of it or is it better to revert it?

Thanks,
Oleg

**Comment by AlexDM0** [comment]
Hi Oleg,

It would be better if you did not include the dist folder in the commits since we could merge automatically then (more likely at least). 

Could you also add to the documentation? Thank you for all the effort! Just to check (since it's not shown in my app) the request is for the develop branch right? We only merge into develop. 

Cheers

>

**Comment by aytech** [comment]
Alex,
OK, I will add the dist folder to gitignore then. Also will update the docs.
Yes, I'm working in develop branch. 

Oleg

**Comment by AlexDM0** [comment]
Great :) sounds good!

**Comment by aytech** [comment]
Alex, I've got one more question: looks like we'll be implementing a number of features to the library which seem to not exist there yet, so I'll most likely have more proposals coming and would like to ask if there's a dedicated place where we could discuss these proposals before starting to work on them?
As obviously the core devs are way more experienced and know better how certain things are best implemented, my current feature being a good example :) 

Thanks,
Oleg

**Comment by AlexDM0** [comment]
Hi Oleg,

Usually this starts out with an issue as feature request. You could then tell us you'd like to implement this yourself and all discussion would take place in the issue. 

Regards,

Alex

**Comment by aytech** [comment]
Perfect, next time I'll take the proper route :) 

Oleg

**Pull request closed without merging**
