### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks. I understand that the version number is not used by bower, but I think it's a bad advice to leave the version number out. I think it's important to be able to (easily and irrefutable) find the actual version number of the library you have actually on your disk.

**Comment by kkirsche** [comment]
Considering it may be moving to NPM anyway I disagree with you pretty strongly. bower/bower#1520 is just one of the discussions. Recommending users even use bower is just bad IMO

**Comment by kkirsche** [comment]
Also their maintainer says they probably won't ever use it: http://stackoverflow.com/questions/24844901/bowers-bower-json-file-version-property

**Comment by josdejong** [comment]
> Considering it may be moving to NPM anyway

I'm not sure what having bower support at all has to do with leaving a version number inside `bower.json` (the issue at hand). But I very strongly hope that everybody will move to npm. Bower did fill a need, but it has a number of fundamental flaws, and having two package managers for (full stack) web development is very unpractical. I would be very happy when Bower will retire.

**Pull request closed without merging**
