### PR TITLE
Chosen

### PR DESCRIPTION
**Pull request by eymiha**
Adds the `chosen` option to change the appearance of a selected or hovered node or edge. _Chosen corresponds to the selected or (if enabled) hovering state of an element._ 

If chosen is false, no visible change occurs when an object is chosen. if true, standard defaults are used for select or hover. If a function is supplied, it is called with a set of values that is used to set the visible change. A chosen.node and chosen.label property may be set with a function on a node's options or the nodes options; a chosen.edge and chosen.label property may be set with a function on an edge's options or the edges option. The sets of changeable options  for nodes, edges and labels is documented.

The `examples/nodes/other/chosen.html` file illustrates the feature.

Existing networks should not be affected.

### CODE REVIEW

**Comment by yotamberk** [comment]
Hi @eymiha, can you please resolve the conflict? I'd like to approve and merge this PR. (sorry for the long wait... We've all been busy)

**Comment by eymiha** [comment]
Sure thing... first thing after the day job... :-)

**Comment by eymiha** [comment]
@yotamberk it should be good to go

**Comment by yotamberk** [comment]
Thanks =) I'll review it again and approve it. Because of the size, I'd like another review before merging it.

**Comment by eymiha** [comment]
a little more cleanup that wasn't a conflict but needed to be done

**Comment by eymiha** [comment]
I understand... I keep adding huge swaths of new functionality. I don't know how to stop.  lol

**Comment by yotamberk** [comment]
It's great! But really difficult to review. I suggest that next PRs will be in bite size portions.... It's really difficult for us to review and accept these enormous code changes... You're better off starting with small features, getting them accepted, and then adding more functionality.

**Comment by eymiha** [comment]
Unfortunately, these changes are deep and resist being broken into small changes without breaking existing networks. I've been making a real effort to keep what's already out there from changing.

**Comment by eymiha** [comment]
I did run all the examples. I wanted to make sure I didn't break anything. :-)

**Comment by eymiha** [comment]
Granted, I didn't check after the merge today.

**Comment by eymiha** [comment]
I fixed an error with the circular image code. And enhanced the edge widths in the chosen example so edge shadow changes show up better.

**Comment by yotamberk** [comment]
@eymiha Can you fix conflicts again please? I hope @mojoaxel will be able to review and accept this the next few days

**Comment by eymiha** [comment]
all should be well again.

**Comment by eymiha** [comment]
I had (painfully) documented the chosen option, but (very sadly) the commit appears to have been lost in a merge since it was written. I will reconstruct the changes. :-(

**Comment by eymiha** [comment]
Documentation was reconstructed and added to the pull request.

**Comment by mojoaxel** [comment]
@eymiha :1st_place_medal: Thanks you so much for this great addition!

**Pull request merged**
