### PR TITLE
fix documentation: properties.nodes doesn't exist, it's properties.items

### PR DESCRIPTION
**Pull request by daattali**

### CODE REVIEW

**Comment by mojoaxel** [comment]
@daattali Thanks! Looks good!
Please merge!

**Comment by mojoaxel** [comment]
should be merged to branch `develop`.

**Comment by mojoaxel** [comment]
fixed with eab9de972d1dc44c4c58673547c0d95ca4abaf24.
@daattali I'm really sorry but your commit is now with my user because I merged them manually into `develop`. Is this ok with you or should I try to revert the changed and wait for you to change your pull request to  the `develop` branch. Sorry again!

**Comment by mojoaxel** [comment]
I reverted my changes.

**Comment by daattali** [comment]
no worries, I don't need my name attached

**Comment by mojoaxel** [comment]
@daattali :-) Thanks. I'll make a proper merge to `develop` in the next day.

**Comment by mojoaxel** [comment]
merged in `develop` with 412a503f4286d30f1baf10a42ef6a7ee5df142f2

**Pull request closed without merging**
