### PR TITLE
Improvement to Graph3D: allow set colors of dots explicitly (in 'dot-color' mode)

### PR DESCRIPTION
**Pull request by ephraimberkovitch**

### CODE REVIEW

**Comment by Tooa** [comment]
Can you create the pull-request for the develop branch?

**Comment by ephraimberkovitch** [comment]
Sure,

sorry for creating it on master, by mistake...

Ephraim

**Comment by Tooa** [comment]
No problem. This is a common problem, which we will tackle with Github pull request templates soon.

**Comment by ephraimberkovitch** [comment]
Regarding indexing the files in the dist folder, the files appear there and are not ignored by .gitignore. Would you like me to add that folder to .gitignore and re-submit the pull request?

**Comment by yotamberk** [comment]
They shouldn't appear in the develop branch.

**Pull request closed without merging**
