### PR TITLE
Timeline - editable option for individual items

### PR DESCRIPTION
**Pull request by danbertolini**
Feature #275, #363 - editable option for individual items. See commit message for details.

This is my first time attempting to contribute to an open source project on Github so please let me know if I have made any rookie mistakes.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks @danbertolini, this is a feature that has long been on our wishlist! Your implementation looks neat. Great that you also updated the docs. I will add a usage example for it.

**Comment by josdejong** [comment]
I've created an example for this feature. I also added a classname `vis-readonly` to complement the `vis-editable` classname.

**Comment by josdejong** [comment]
@danbertolini I've just released v4.3.0 with support for editable items :)

**Comment by danbertolini** [comment]
Great, happy to contribute.

**Pull request merged**
