### PR TITLE
Network: DRY code in Label for parsing markup

### PR DESCRIPTION
**Pull request by wimrijnders**
This gets rid of a major eyesore for me. The accumulator object was identical for HTML and  Markdown.

In addition, the parsing has been refactored. Common elements have been DRY'd and the logic of the parsing has been made more comprehensible.

Unit tests for parsing HTML tags and Markdown are already present. These were used to verify that this refactoring is good.

### CODE REVIEW

**Comment by macleodbroad-wf** [comment]
Suggest pre-compiling regexes as per performance tip on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions

See attached patch.

[precompile-regex.diff.zip](https://github.com/almende/vis/files/1385036/precompile-regex.diff.zip)

**Comment by wimrijnders** [comment]
OK. Went with this and expanded on it. Also code changes to make it work nice, some code cleanup.

This is starting to look a lot like [memoization](https://en.wikipedia.org/wiki/Memoization).

**Comment by wimrijnders** [comment]
BTW, superfluously, long live unit tests. With the markup testing already in place, changing this was with 100% reliability.

**Comment by wimrijnders** [comment]
I'm refraining with further refactoring. I still see some good thing to do here, some other time.

**Comment by wimrijnders** [comment]
Any other good ideas? Looking forward to your review.

**Pull request merged**
