### PR TITLE
Added showX(YZ)Axis to Graph3d

### PR DESCRIPTION
**Pull request by nmehrle**
Added options showXAxis, showYAxis, showZAxis to Graph3d. Default to true. Setting one to false disables drawing of respective axis, axis label, tick marks and tick mark labels. Setting all three to false and show grid to false allows display of data with no supplementary lines

### CODE REVIEW

**Comment by mojoaxel** [comment]
:+1:

**Comment by mojoaxel** [comment]
@nmehrle Thanks. But can you please add documentation for the new options.

**Comment by mojoaxel** [comment]
Looks like @nmehrle is too busy to add documentation for this. Maybe @wimrijnders wants to enhance this PR?

**Comment by nmehrle** [comment]
Okay, sorry I was quite busy, but I have gotten around to updating the graph3d docs and the playground example. 

I'm not too familiar with github, but on my branch it says 5 files changed (the relevant files for adding the feature/docs/example) not the many changes here, so I'm not sure if its right or not

**Comment by yotamberk** [comment]
Why are there so many changes? I think yo've accidentally pulled from the `master` branch

**Comment by nmehrle** [comment]
I don't think I pulled from master. When I look at my develop branch, it says 5 commits ahead (which are the changes I made and merging to the most recent almende/vis/develop branch), so I'm not sure whats going on here. I don't know how to update this to have the same changes as in my branch

**Comment by yotamberk** [comment]
@mojoaxel Can you help here? I think there is some confusion with pulling issues.

**Comment by mojoaxel** [comment]
Something went wrong here. I'm not sure.
What could help is maybe a `git rebase develop` on the nmehrle:develop branch.

**Comment by mojoaxel** [comment]
@nmehrle Can you try to rebase? The conflicts should not be very bad bacause there was not much change in chart3d.

**Comment by mojoaxel** [comment]
If nothing works I'll cherry-pick the commits into a new branch.

**Comment by nmehrle** [comment]
hmm git rebase develop just says:
>Current branch develop is up to date.

I can try closing this pull request and making a new one, I think the issue is that this is tracking the commits made in between my contributions and those show up as changes

**Pull request closed without merging**
