### PR TITLE
Added allDraggable option for timeline to support dragging unselected item

### PR DESCRIPTION
**Pull request by liuqingc**
I added an option for timeline so that we could drag the item even it is not selected in the timeline. Please review. Thanks!

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks for your PR @liuqingc.

We've had this behavior in the the past: moving items without having them selected. However, in practice this worked out very badly: people can easily move items accidentally (and unnoticed) whilst moving the timeline. It's worse when the Timeline is crowded with items. My opinion is that this behavior is undesirable and also should not be supported as an option.

**Comment by liuqingc** [comment]
Hi @josdejong , thank you for your reply.

I understand the disadvantage of having this feature: people could move items accidentally without noticing they had moved the items. There are also disadvantages of not having this feature: 1) People might think that the items are not draggable if they fail to drag the unselected items. It could take some time for them to figure out how to drag the item. 2) Even when people know that they have to select the item first, they may still attempt to drag them but ended up dragging the timeline. 

I have been using the library for a while and people are always complaining that they are not able to move the item. We don't have a lot of items on the timeline and the items are of the same size. If an item was moved, there would be a content refreshing within the item. In such cases, we could avoid the disadvantage of having this feature.

I think the feature has two sides and the option could leave people choices to decide depending on their use cases.

**Comment by josdejong** [comment]
> I think the feature has two sides and the option could leave people choices to decide depending on their use cases.

yeah, you're right with that. Well ok then let's add this new feature. 

I'm just thinking a bit about what would be the best name, `allDraggable` sounds a bit vague. How about something like `alwaysDraggable`, `itemsAlwaysDraggable`, ... ?

**Comment by liuqingc** [comment]
Glad to hear that. We could go with 'itemsAlwaysDraggable' which is self-explaining.

Thanks,
Liuqing

**Comment by josdejong** [comment]
Sounds good, lets go for `itemsAlwaysDraggable`. Can you update your PR accordingly? Then I will merge it. Thanks!

**Comment by liuqingc** [comment]
Done. I have update the codes. Thanks.

**Comment by josdejong** [comment]
Thanks!

**Pull request merged**
