### PR TITLE
Enable unit testing for module Network

### PR DESCRIPTION
**Pull request by wimrijnders**
Adds mocks for certain components, in order to let module `Network` be run in unit tests.

### Changes

- Create a mock object for `hammer.js` when running browserless. The inspiration is taken from [here](https://github.com/uber/deck.gl/pull/658)
- Create a mock function for `window.requestAnimationFrame()` when running browserless in `network/modules/CanvasRenderer.js`
- Added unit test for `Network` to show that unit testing for it now works
- Fixed naming of container in `test/Graph3d.test.js`

Since `hammer.js` is also used in other modules, this fix is potentially an enabler for full-module unit tests for those as well.

----

### Update

- Added fix for failing unit test. This was actually a unit test problem!
- Added unit tests for loading examples. This is because I noticed that some examples are failing
- Added fix to `Network` for example `disassemblerExample`. This is just to make the unit tests for this issue succeed.

I noticed that some examples are not working. I will scan them all and make a separate PR to fix all of these.

### CODE REVIEW

**Comment by yotamberk** [comment]
@wimrijnders test is failing =(

**Comment by wimrijnders** [comment]
I know. Still thinking of how to fix this 😭 .

**Comment by wimrijnders** [comment]
😅 I figured it out. Unit tests fixed and more.

**Comment by yotamberk** [comment]
@wimrijnders conflicts =(

**Comment by wimrijnders** [comment]
Conflicts fixed.

**Pull request merged**
