### PR TITLE
Don't pass non-string values to Date.parse

### PR DESCRIPTION
**Pull request by jimmed**
Fixes: https://github.com/almende/vis/issues/2490

### CODE REVIEW

**Comment by jimmed** [comment]
@yotamberk I've changed the PR base to `develop` - can you re-review?

**Comment by yotamberk** [comment]
Thanks @jimmed !

**Comment by jimmed** [comment]
Amazing! When can I expect this to hit a version on NPM?

**Comment by mojoaxel** [comment]
@jimmed Please create a new pull request. We had to revert this one. Please make sure to base your changes on an up-to-date develop branch. Thanks.

**Comment by jimmed** [comment]
@mojoaxel I've just had a check on the develop branch, and it seems like [my fix would be redundant there](https://github.com/almende/vis/blob/develop/lib/util.js#L400).

**Comment by jimmed** [comment]
@mojoaxel Check #2534 - identical but on the develop branch

**Pull request merged**
