### PR TITLE
Fix issue #3500

### PR DESCRIPTION
**Pull request by justinharrell**
This fixes unconnected edges not showing back up if nodes are modified or added that connect them.

I tried a couple approaches, this could probably be optimized some with deeper changes, but I choose to keep the fix as simple as possible.

### CODE REVIEW

**Comment by wimrijnders** [comment]
Fixes #3500

**Comment by wimrijnders** [comment]
While the code fix is 100% good, I neglected to observe that there is no regression test for this fix. Do you have the energy to add that?

I'm thinking of some network where a node is removed and then added again. The test would be that the edges for that node have reconnected.

If you don't feel like adding that, I'm prepared to do it myself. It's my oversight.

**Comment by justinharrell** [comment]
I pushed a change with a test and some white-space cleanup into the fix branch, would that be a new PR?

**Comment by wimrijnders** [comment]
Sincerely thanks for your effort. I've never even tried pushing to a merged PR before, is it possible?
Let's not tart fate. A new PR would do nicely.

**Pull request merged**
