### PR TITLE
Fixes #2584

### LINKED ISSUE #2584: Webpage: Missing Example Screenshots
I updated the example overview pages in the gh-pages branch. There are still a view screenshots missing.

### PR DESCRIPTION
**Pull request by macleodbroad-wf**
Adds network thumbnails to examples pages
@wimrijnders

### CODE REVIEW

**Comment by macleodbroad-wf** [comment]
Oddly, I searched for references to other PNGs in the documentation/source and found none.

To QA this branch, pull it down and open the `network_examples.html` to verify that the thumbnails appear as expected.

**Comment by wimrijnders** [comment]
> pull it down and open the network_examples.html to verify that the thumbnails appear as expected.

Did this and in the process got a real boost in my `git` skills. Also, TIL that option `--depth=1` is supremely useful when dealing with big repo's that have big histories. I hereby thank you for throwing this challenge in my path.

And so, finally being able to have a look at your fixes, here's my scathing review: **It's bloody perfect**.

**Comment by wimrijnders** [comment]
The only thing I can think of remarking on is the image for 'manipulation edit edge no drag', which is slightly bigger than the other images and therefore overlaps with 'navigation buttons and keyboard shortcuts'.

However, it is also obvious to me that you went out of your way to clearly show the buttons of the manipulation toolbar. With this in mind, I find that you solution is better than trying to force the image into the same dimensions as the rest. So :+1:.

**Comment by mojoaxel** [comment]
@macleodbroad-wf Thanks nice job by the way! Your help is highly appreciated!

**Comment by mojoaxel** [comment]
🎉  Now every test has a thumbnail again: http://visjs.org/network_examples.html

@All: We should make sure, that every new example comes with a new thumbnail!

**Pull request merged**
