### PR TITLE
Update README.md at 'Exclude external libraries'

### PR DESCRIPTION
**Pull request by yxh10**
The command showed needs to be updated to include the preset es2015

### CODE REVIEW

**Comment by mojoaxel** [comment]
@yotamberk Why did we merge this directly into the master branch? I did not noticed it during ma review. I think we should revert!

**Comment by yotamberk** [comment]
F*** i didnt notice... we should revert... Sorry

**Comment by mojoaxel** [comment]
Ok, I'll going to revert this maually.
@yxh10 Can you please create a new Pull request to the develop-branch!

**Comment by mojoaxel** [comment]
Done!

**Pull request merged**
