### PR TITLE
Added mouseover and mouseout events to the time bar.  This currently wor...

### PR DESCRIPTION
**Pull request by andyflatt**
...ks with RangeItems only.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks @andyflatt! 

A few remarks:
- It would be great if you could implement it for each of the item types. 
- Also, it will be better performance wise to only attach a `mouseover` and `mouseout` event listener to the ItemSet rather than to each individual item (event delegation).
- Can you please only commit the changes in the source, and not in the generated files in `/dist`?

**Comment by andyflatt** [comment]
Ok, I made these changes for a demo last week so I was aware that they are not complete.  Ill try and find time to correct them in the next fortnight.

**Comment by andyflatt** [comment]
I have implemented this support for box and point

Because of the difficulties of event delegation on mouseover, I can not see how I can use event delegation from the itemset.  Do you have any suggestions?

For the last commit I did not commit the generated files.

**Comment by andyflatt** [comment]
@josdejong  You closed the issue without merging in the changes.  I implemented what you suggested and asked some questions.  How come you do not want this hover support?

**Comment by josdejong** [comment]
Maybe this happened because I deleted the develop branch and replaced it with the (released) `v4` branch. I've reopened this issue. I think I overlooked your open PR, sorry. We should get this merged into the code again.

**Comment by andyflatt** [comment]
Does this code need any more work before it can be merged?

**Comment by josdejong** [comment]
@andyflatt I think your latest version was good (except for no need to commit changes in `/dist`). Would be great if you could redo your PR, sorry for the inconvenience.

**Comment by The-Dub** [comment]
Hi,
I was trying to find if there was a mouseover event in the vis.timeline library.
Did you do implemented that functionality ?

Great library btw, thanks !

**Comment by AlexDM0** [comment]
Hi,

What do you need these event for? We have not had a usecase that requires these events.  

Cheers

**Comment by The-Dub** [comment]
I created an interactive timeline with images, and tooltips attached to those images are created on-the-fly. I needed to grab the date (or the item #) to do some matching behind to show the right information.

I worked my way around with mouseover inside the timeline triggering a click event, and then grabbing the info from that (simplest way I could find).

So not a big deal, if it's a unique request, don't bother implementing it, but I think it could be use for interactivity outside the timeline.

thanks for the answer ! ;)

**Comment by andyflatt** [comment]
I remember seeing this feature on the wishlist on the vis website.  This merge request allows for 'mouseover' and 'mouseout' events in the timeline.  I implemented this because I was using the timeline in conjunction with a the map and wanted to highlight things on the map on mouse over.

Do I need to redo the PR?  What should I do differently on a new PR?  Is it to just not include the dist folder?

@The-Dub Please pull the develop branch of https://github.com/andyflatt/vis to see if it satisfies you requirement.

**Comment by The-Dub** [comment]
I'll take a look at that today.
Thanks !

**Comment by andyflatt** [comment]
Created https://github.com/almende/vis/pull/1367 for the new pull request

**Pull request closed without merging**
