### PR TITLE
Multiple base edges in clustered edge

### PR DESCRIPTION
**Pull request by wimrijnders**
This fix adjusts the clustering edges so that they can refer to multiple edges instead of just one.

Fix for #3245.
   
### Multiple base edges can be assigned to single clustering edge

Basically, the original single value field `clusteringEdgeReplacingId` has been replaced by the array-field `clusteringEdgeReplacingIds`, and all associated operations on it have been adjusted.
    
### Deprecated method `clustering.getBaseEdge()`
This API method is now insufficient, since multiple base edges can be returned.
    
- Added replacing method `clustering.getBaseEdges()`
- Adjusted example `changingClusteredEdgeNodes` for the new method. This is the *only* place where `getBaseEdge()` was used
- Adjusted documentation for new method and deprecation old method.
    
Method `getbaseEdge()` should now be considered `deprecated`, and in due time should be removed.

### CODE REVIEW

**Comment by yotamberk** [comment]
@wimrijnders It seems to have conflicts that need to be resolved. 
I have a problem with this PR. I don't want to accept a PR with a deprecation because it means we need to update to a major version. I would leave the method and add a `// TODO: deprecate in 5.0.0` to avoid major release.

**Comment by wimrijnders** [comment]
> I would leave a note to deprecate the method in v5.0.0 in a TODO

That's perfectly reasonable; I'll do that.
TBH I am not aware how major/minor releases are handled; I asked about this in the lobby. But I think this is a perfectly good idea.

**Comment by wimrijnders** [comment]
Conflict fixed

**Comment by nanialves** [comment]
How to use this feature work for [this](https://stackoverflow.com/questions/49626545/cluster-multiple-edges-between-two-nodes)? In other words, this interact like clustered nodes?

**Pull request merged**
