### PR TITLE
Added pt-br locale to network

### PR DESCRIPTION
**Pull request by chrisbenseler**
I have added the pt-br messages to the network from Vis.

### CODE REVIEW

**Comment by mojoaxel** [comment]
@chrisbenseler Thank You very much!
Sadly we expect pull-request against the `develop` branch not the master branch. 
Also you deleted images in the dist folder. If it is too much of a hassle to switch the branch now I'll merge your PR manually in `develop`.

But please reset the dist folder first by doing this in your `master` branch:
```bash
git checkout -- dist
git push --force
```
Thanks again!

**Comment by chrisbenseler** [comment]
@mojoaxel I'll do it.

About the images, I didn  delete it manually. By some (unknown reason) for me, they wrere delete after I ran 'npm run build' :S

**Comment by mojoaxel** [comment]
> The build is deleting those images. Maybe it's something with my OS? I'm on an Ubuntu 16.04

That's not your fault! I think the dist folder should be ignored in the `develop` branch. But I'm not yet sure how to do this elegantly without breaking the merging with `master` before a release.
The best way at the moment ist to reset the dist folder (`git checkout -- dist`) before pushing the changes.

Nice! Im also on ubuntu 16.04 ;-)

**Comment by mojoaxel** [comment]
replaced with #2052

**Pull request closed without merging**
