### PR TITLE
Added 2D line drawing method

### PR DESCRIPTION
**Pull request by wimrijnders**
DRY the drawing of a single 2D line.

### CODE REVIEW

**Comment by wimrijnders** [comment]
:-) I now feel the need to buy you a beer. You're not anywhere close to the Netherlands I presume?

**Comment by wimrijnders** [comment]
Wow you guys are so responsive right now. I can barely keep up.

**Comment by yotamberk** [comment]
Yeah well I'm a recent member of the team and I happen to be on holiday so I can afford to be online =)
Not near Netherlands but I appreciate your appreciation!

I hope we can get this library very active and have many more contributors! We appreciate your help and PRs!

**Comment by wimrijnders** [comment]
OK one more for today, one that I consider important.
As you may have noticed, I'm mostly DRY'ing the code. Next one is a DRY of a big important chunk.

**Pull request merged**
