### PR TITLE
Labels on Graph2d

### PR DESCRIPTION
**Pull request by tobeee**
This pull request allows for Labels (ie text nodes) to be added to individual items on a Graph2d instance

I improved on the code created in the issue (https://github.com/almende/vis/issues/630#issuecomment-74227944) to expand how on it might function. I've also added offsets and classes on each label

Hopefully someone will find it useful :)

### CODE REVIEW

**Comment by tobeee** [comment]
Just to be clear this pull request allows for Labels (ie text nodes) to be added to individual items on a Graph2d instance

**Comment by AlexDM0** [comment]
Hi Toby,

I'll check it out tomorrow! Thanks!

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi Toby,

Could you add documentation for the added options and remove the 3.14.5.9.flags.json file from the commit?

Cheers

**Comment by tobeee** [comment]
Done - is it OK?



On Tue, Feb 17, 2015 at 10:22 AM, Alex <notifications@github.com> wrote:

> Hi Toby,
>
> Could you add documentation for the added options and remove the
> 3.14.5.9.flags.json file from the commit?
>
> Cheers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/almende/vis/pull/635#issuecomment-74645925>.
>



-- 
Toby Green

**Comment by AlexDM0** [comment]
Hi Toby,

Yes thank you! For some reason I couldn't get git to recognise the pull through commandline but I have pushed the merged pull request back to develop.

Thanks for contributing!

**Pull request closed without merging**
