### PR TITLE
Create Export.js file

### PR DESCRIPTION
**Pull request by hadjloo**
Add ability to save current view of canvas

### CODE REVIEW

**Comment by AlexDM0** [comment]
Hi,

I'm not sure why we would need this actually. Why would we want to include this? 

If you feel there is a solid usecase then I'd imagine this to be in the network code, exporting the network and we'd need documentation. 

Regards

**Comment by hadjloo** [comment]
As a network admin, there is always a need to have a quick look of network map, to use it in presentations or to describe it to managers, so having a feature to export the network map will come handy

for documentation this is the sample case

1 - Add a link on page for import, it should have a selector, either css class or id
2 - call **ExportCanvasToPng()** with these parameter
 2.1 - **canvasId**: selector of network map canvas
 2.2 - **downloadLinkId**: selector of download link
 2.3 - **exportFileName**: file name to download

**Comment by AlexDM0** [comment]
Why not network.exportToPNG()?

**Comment by hadjloo** [comment]
That is not a bad idea, but actually I think it could be used in other libraries too. I'm not sure in other libraries it could be counted as a valuable feature,but it is better to have a universal feature which is consistent in all libraries,  instead of a feature that is available in one library and missed in others

**Comment by AlexDM0** [comment]
Well we are ONE library ;). There are many things different from others. Specifically, vis is not a util lib. 

Anyone can google and find this method as stackoverflow has it. Anyone who needs it can write it themselves or copy it over. Supporting this is actually more work than having people who need it Google, hence my question of do we need it. If we add it, next feature requests are: can we export it to jpg, pdf, vector, can we put in custom sizes etc. is that really worth it? The aim for vis is to be an interactive network. Not an offline image making tool. There are plenty of those. 

Regards

**Comment by hadjloo** [comment]
If the problem is supporting other formats, I agree to not include it in library, otherwise have a tiny export feature could come handy, all in all, I agree it can be only added in Network lib

**Comment by AlexDM0** [comment]
Unless you want to commit to expanding the feature based on feedback Id accept it if integrated in network. If not, then I'd rather not commit to an export feature that won't grow past the initial commit.

**Comment by hadjloo** [comment]
I moved the function to network library, I'll close this, and create another pull request

**Comment by hadjloo** [comment]
I merges the pull request

**Comment by AlexDM0** [comment]
Hi, I'm not sure we need to supply the canvas ID when its in the network? You'll also need to add it to the documentation.

**Pull request closed without merging**
