### PR TITLE
Improvement for camera 3d moving

### PR DESCRIPTION
**Pull request by linuxnotes**
Improvement of camera moving for 3d graph

### CODE REVIEW

**Comment by yotamberk** [comment]
Hey @linuxnotes , Thanks for the PR! Your PR is from the wrong branch to the wrong branch. Try again please in to the develop branch.

**Comment by mojoaxel** [comment]
@wimrijnders Maybe you want to have a look a this? Maybe it's time to merge the `3d-camera-orientation` finally?

**Comment by wimrijnders** [comment]
привет @linuxnotes, хотя бы мне нравится видеть работу русскового программиста, по-моему лучше сохранять комментары по-англиски. Позвольте измени этот предложение.

Also, please heed the comment of @yotamberk. New stuff should go into the develop branch.

**Comment by mojoaxel** [comment]
@linuxnotes Thanks for your changes! But as far as I understand @wimrijnders the `3d-camery-orientation` branch is still not ready to get merged into develop. see also #2007.

@wimrijnders and @linuxnotes Feel free to improve the existing `3d-camery-orientation` branch and create a pull-request if you think it is ready to get merged into `develop`.

**Comment by wimrijnders** [comment]
@mojoaxel understood. I'll do any improvements in a separate PR.

**Comment by mojoaxel** [comment]
@linuxnotes and @wimrijnders I just rebased the `3d-camery-orientation`branch on the current develop to keep it up to date. Please pull again.

**Comment by linuxnotes** [comment]
Ok. Thanks.

**Comment by wimrijnders** [comment]
OK pulled this branch. Everything works fine.

**Pull request merged**
